# SCREEN SETTINGS
HEIGHT = 600
WIDTH = 800

# BALL SETTINGS
MIDDLE_DEAD_ZONE = 60
BALL_RESET_PAUSE = 15
BALL_SPEED = 10

# PADDLE SETTINGS
PADDLE_LENGTH = 100
PADDLE_SPEED = 20

# TEXT SETTINGS
ALIGNMENT = 'center'
FONT = ('Courier', 40, 'bold')

# GAME SETTINGS
GAME_SPEED = 0.015
WIN_POINTS = 10
